# Permalinks
permalink:        /:title

# Setup
title:            Priya
tagline:          A hard working Tech Enthusiast
description:      A hard working Tech Enthusiast
url:              https://cherrywine04.github.io
baseurl:          /Bootstrap-4-Jekyll-Theme
rawurl:	          
# Add this and create headline.html in _includes directory
# headline: true         
# Add your google_analytics ID if you need it
# google_analytics: 

# Pagination number
paginate:         10

# category page
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
