# Permalinks
permalink:        /:title

# Setup
title:            Test Site
tagline:          Test tagline
description:      Test description
url:              
baseurl:          /Bootstrap-4-Jekyll-Theme

# Pagination number
paginate:         10

# category page
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"